Text_ItsATV:
	.string "Es una TV.$"

Text_MyReflection:
	.string "¡Mi reflejo!\n"
	.string "¡Qué guay!$"

Text_AncientPokemonReplica:
	.string "It's a replica of an ancient\n"
	.string "{POKEMON}.$"

Text_DistinguishedStatue:
	.string "A {POKEMON} statue…\n"
	.string "It looks very distinguished.$"

Text_PictureBookShelf:
	.string "It's a whole collection of {POKEMON}\n"
	.string "picture books!$"

Text_BookShelf:
	.string "Está llena de libros complejos.$"

Text_PokemonCenterBookShelf:
	.string "{POKEMON} magazines!\n"
	.string "{POKEMON} PAL…\p"
	.string "{POKEMON} HANDBOOK…\n"
	.string "{POKEMON} GRAPH…$"

Text_Vase:
	.string "This vase looks expensive…\n"
	.string "Peered inside…\p"
	.string "But, it was empty.$"

Text_EmptyTrashCan:
	.string "It's empty.$"

Text_ShopShelf: @ 82A82BF
	.string "Lots of {POKEMON} merchandise!$"

Text_Blueprint:
	.string "A blueprint of some sort?\n"
	.string "It's too complicated!$"
