gText_SetClock_WokeMeUp::
	.string "………………………………………………\n"
	.string "………………………………………………\p"
	.string "¡Zzz…! ¿Qué…?\n"
	.string "¡Me despertaste!\p"
	.string "¿Te importaría decirme la hora?$"

gText_Oak_Welcome:: @ 82C897B
	.string "¡Hola! ¡Perdona por la espera!\p"
	.string "¡Estás en el mundo de los {POKEMON}!\p"
	.string "Me llamo OAK.\p"
	.string "¡Pero la gente me llama\n"
	.string "PROFESOR {POKEMON}!\p"
	.string "$"

gText_Oak_Pokemon::
	.string "¡Este mundo está…$"

gText_Oak_Pokemon2::
	.string "habitado por criaturas\n"
	.string "llamadas {POKEMON}!\p"
	.string "$"

gText_Oak_MainSpeech::
	.string "La gente y los {POKEMON} conviven\n"
	.string "apoyándose unos a otros.\p"
	.string "Algunos juegan con los {POKEMON},\n"
	.string "otros luchan con ellos.\p"
	.string "$"

gText_Oak_MainSpeech2::
	.string "Pero aún hay muchas cosas que\n"
	.string "no sabemos.\p"
	.string "Quedan muchos misterios\n"
	.string "por resolver.\p"
	.string "Por eso estudio a diario\n"
	.string "a los {POKEMON}.\p"
	.string "Bueno, suficiente sobre mí.\n"
	.string "Cuéntame un poco sobre ti.\p"
	.string "$"

gText_Oak_BoyOrGirl::
	.string "¿Eres un chico?\n"
	.string "¿O una chica?$"

gText_Oak_WhatsYourName::
	.string "Veamos, ¿cómo dijiste que te\n"
	.string "llamabas?\p"
	.string "$"

gText_Oak_SoItsPlayer::
	.string "Vale…\n"
	.string "Así que te llamas {PLAYER}.$"

gText_Oak_AreYouReady::
	.string "{PLAYER}, ¿estás preparad{KUN}?\p"
	.string "Tu propia leyenda {POKEMON} está\n"
	.string "a punto de comenzar.\p"
	.string "Te divertirás y te enfrentarás\n"
	.string "a duros desafíos.\p"
	.string "¡Te espera un mundo de sueños y\n"
	.string "aventuras con {POKEMON}! ¡Vamos!\p"
	.string "¡Nos vemos!$"
