gText_SetClock_WokeMeUp::
	.string "………………………………………………\n"
	.string "………………………………………………\p"
	.string "Zzz… ¿Eh? ¿Qu…?\n"
	.string "¡Me has despertado!\p"
	.string "¿Podrías mirar el reloj por mí?$"

gText_Oak_Welcome:: @ 82C897B
	.string "¡Hola! Perdona la espera.\p"
	.string "¡Bienvenido al mundo de {POKEMON}!\p"
	.string "Me llamo OAK.\p"
	.string "La gente me conoce cariñosamente\n"
	.string "como el PROFESOR {POKEMON}.\p"
	.string "$"

gText_Oak_Pokemon::
	.string "Este mundo…$"

gText_Oak_Pokemon2::
	.string "…está habitado por criaturas\n"
	.string "llamadas {POKEMON}.\p"
	.string "$"

gText_Oak_MainSpeech::
	.string "Los humanos y los {POKEMON} viven\n"
	.string "juntos apoyándose unos a otros.\p"
	.string "Algunos juegan con los {POKEMON},\n"
	.string "otros luchan con ellos.\p"
	.string "$"

gText_Oak_MainSpeech2::
	.string "Pero, a pesar de ello, aún no\n"
	.string "sabemos todo sobre los {POKEMON}.\p"
	.string "Siguen existiendo muchos misterios\n"
	.string "por resolver.\p"
	.string "Por eso estudio los {POKEMON} como\n"
	.string "profesión cada día.\p"
	.string "Bueno, basta de mí.\n"
	.string "Cuéntame un poco sobre ti.\p"
	.string "$"

gText_Oak_BoyOrGirl::
	.string "¿Eres un chico?\n"
	.string "¿O una chica?$"

gText_Oak_WhatsYourName::
	.string "Veamos, ¿cómo dijiste que te\n"
	.string "llamabas?\p"
	.string "$"

gText_Oak_SoItsPlayer::
	.string "Vale…\n"
	.string "Así que te llamas {PLAYER}.$"

gText_Oak_AreYouReady::
	.string "{PLAYER}, ¿estás preparad{KUN}?\p"
	.string "Tu propia aventura {POKEMON} está\n"
	.string "a punto de comenzar.\p"
	.string "Te esperan momentos divertidos y\n"
	.string "retos difíciles.\p"
	.string "¡Un mundo de sueños y aventuras\n"
	.string "con {POKEMON} te aguarda! ¡Vamos!\p"
	.string "¡Hasta luego!$"
