gText_ObtainedTheItem::
	.string "¡Obtuviste {STR_VAR_2}!$"

gText_TheBagIsFull::
	.string "La MOCHILA está llena…$"

gText_PutItemInPocket::
	.string "{PLAYER} puso {STR_VAR_2}\n"
	.string "en el BOLSILLO de {STR_VAR_3}.$"

gText_PlayerFoundOneItem::
	.string "¡{PLAYER} encontró {STR_VAR_2}!$"

gText_TooBadBagIsFull::
	.string "¡Mala suerte!\n"
	.string "La MOCHILA está llena…$"

gText_PlayerPutItemInBag::
	.string "{PLAYER} puso {STR_VAR_2}\n"
	.string "en la MOCHILA.$"

gText_ObtainedTheDecor::
	.string "¡{PLAYER} obtuvo {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
	.string "¡Mala suerte! No queda sitio\n"
	.string "para {STR_VAR_2}…$"

gText_FruitBearingTree:
	.string "Es un árbol de bayas.\p"
	.string "¡Oh!\n"
	.string "¡Es una {STR_VAR_2}!$"

gText_FruitBearingTreeNothingHere:
	.string "Es un árbol de bayas.\p"
	.string "Parece que no hay nada…$"

gText_TheDecorWasTransferredToThePC::
	.string "Se envió {STR_VAR_2} al PC.$"

gText_FruitBearingTreeBagFull:
	.string "Pero la MOCHILA está llena…$"
