Text_BootUpPC:
	.string "{PLAYER} encendió el PC.$"

gText_WhichPCShouldBeAccessed::
	.string "¿A qué PC quieres acceder?$"

gText_AccessedSomeonesPC::
	.string "Accedió al PC de alguien.$"

gText_StorageSystemOpened::
	.string "Acceso al Sistema de\n"
	.string "Almacenamiento de {POKEMON}\l"
	.string "concedido.$"

gText_AccessedPlayersPC::
	.string "Accedió al PC de {PLAYER}.$"

gText_AccessedLanettesPC::
	.string "Accedió al PC de BILL.$"
