gText_PkmnTransferredSomeonesPC::
	.string "{STR_VAR_2} fue enviado al PC\n"
	.string "de alguien.\p"
	.string "Se ha guardado en la CAJA\n"
	.string "“{STR_VAR_1}”.$"

gText_PkmnTransferredLanettesPC::
	.string "{STR_VAR_2} fue enviado al PC\n"
	.string "de BILL.\p"
	.string "Se ha guardado en la CAJA\n"
	.string "“{STR_VAR_1}”.$"

gText_PkmnTransferredSomeonesPCBoxFull::
	.string "La CAJA “{STR_VAR_3}” del PC\n"
	.string "de alguien estaba llena.\p"
	.string "{STR_VAR_2} fue enviado a la CAJA\n"
	.string "“{STR_VAR_1}”.$"

gText_PkmnTransferredLanettesPCBoxFull::
	.string "La CAJA “{STR_VAR_3}” del PC\n"
	.string "de BILL estaba llena.\p"
	.string "{STR_VAR_2} fue enviado a la CAJA\n"
	.string "“{STR_VAR_1}”.$"

gText_NoMoreRoomForPokemon::
	.string "¡No queda sitio para más {POKEMON}!\p"
	.string "¡Las CAJAS {POKEMON} están llenas!$"

gText_PlayerObtainedTheMon::
	.string "¡{PLAYER} obtuvo\n"
	.string "el {STR_VAR_1}!$"

gText_NicknameThisPokemon::
	.string "¿Quieres dar un nombre al\n"
	.string "{STR_VAR_1} que has recibido?$"
