gText_NurseIntro_Morning::
	.string "¡Buenos días!\n"
	.string "Bienvenid{KUN} a nuestro CENTRO {POKEMON}.\p$"

gText_NurseIntro_Day::
	.string "¡Hola!\n"
	.string "Bienvenid{KUN} a nuestro CENTRO {POKEMON}.\p$"

gText_NurseIntro_Night::
	.string "¡Buenas tardes! Ya es tarde.\n"
	.string "Bienvenid{KUN} a nuestro CENTRO {POKEMON}.\p$"

gText_NurseIntro_Common::
	.string "Podemos curar a tus {POKEMON} y\l"
	.string "dejarlos en plena forma.\p"
	.string "¿Quieres que curemos a tus {POKEMON}?$"

gText_IllTakeYourPkmn::
	.string "De acuerdo, ¿me enseñas tus {POKEMON}?$"

gText_RestoredPkmnToFullHealth::
	.string "Gracias por esperar.\n"
	.string "Tus {POKEMON} están en plena forma.$"

gText_WeHopeToSeeYouAgain::
	.string "¡Esperamos volver a verte pronto!$"

gText_WelcomeCutShort::
	.string "¡Hola!\n"
	.string "Bienvenid{KUN} a nuestro CENTRO {POKEMON}.\p"
	.string "Podemos curar a tus {POKEMON} y\l"
	.string "dejarlos en plena forma.\p"
	.string "¿Quieres que…$"

gText_NoticesGoldCard::
	.string "Esa tarjeta…\n"
	.string "¿Será… la TARJETA ORO?!\p"
	.string "¡Oh, el color dorado brilla!\n"
	.string "¡Las cuatro estrellas parecen chispear!\p"
	.string "He visto a varios ENTRENADORES con\n"
	.string "TARJETA PLATA, pero, {PLAYER},\l"
	.string "¡tú eres el primer ENTRENADOR al que\l"
	.string "veo con TARJETA ORO!\p"
	.string "De acuerdo, {PLAYER}, ¡permíteme\n"
	.string "el honor de curar a tus {POKEMON}!$"

gText_YouWantTheUsual::
	.string "¡Me alegra verte, {PLAYER}!\n"
	.string "Lo de siempre, ¿verdad?$"

gText_IllTakeYourPkmn2::
	.string "De acuerdo, me quedo con tus {POKEMON}\n"
	.string "unos segundos.$"

gText_ThankYouForWaiting::
	.string "Gracias por esperar.$"

gText_WeHopeToSeeYouAgain2::
	.string "¡Esperamos volver a verte pronto!$"
