Text_Bill_Greeting_Morning:
	.string "Good morning!\p"
	.string "This is the {POKEMON} STORAGE SYSTEM\n"
	.string "ADMINISTRATION SERVICE.\p$"


Text_Bill_Greeting_Day:
	.string "Good day!\p"
	.string "This is the {POKEMON} STORAGE SYSTEM\n"
	.string "ADMINISTRATION SERVICE.\p$"


Text_Bill_Greeting_Night:
	.string "Good evening!\p"
	.string "This is the {POKEMON} STORAGE SYSTEM\n"
	.string "ADMINISTRATION SERVICE.\p$"


Text_Bill_WhosCalling:
	.string "Who's calling?\p"
	.string "{PLAYER}, is it?\n"
	.string "Hang on a sec…\p"
	.string "…\n"
	.string "…\p$"


Text_Bill_StartingOnThisBox_Variant1:
	.string "Thanks for waiting!\p"
	.string "{PLAYER}, you're starting on the BOX\n"
	.string "named “{STR_VAR_1}” right now.\l"
	.string "Great name, by the way.\p$"


Text_Bill_StartingOnThisBox_Variant2:
	.string "Thanks for waiting!\p"
	.string "Right now, {PLAYER}, you're using the\n"
	.string "BOX named “{STR_VAR_1},” right?\l"
	.string "That's a good name right there.\p$"


Text_Bill_StartingOnThisBox_Variant3:
	.string "Thanks for waiting!\p"
	.string "So, {PLAYER}, your BOX is called\n"
	.string "“{STR_VAR_1},” right?\l"
	.string "Not just anyone would use that name.\p$"


Text_Bill_RoomRemaining:
	.string "Okay, including the space left in\n"
	.string "“{STR_VAR_1},” you have room for {STR_VAR_2}\l"
	.string "more {POKEMON} in the PC.\p"
	.string "Get out there and keep collecting!$"


Text_Bill_LittleRoomRemaining:
	.string "Okay, including the space left in\n"
	.string "“{STR_VAR_1},” you only have room for\l"
	.string "{STR_VAR_2} more {POKEMON} in the PC.\p"
	.string "Soon, you'll have to release some\n"
	.string "{POKEMON} if you want to catch more.$"


Text_Bill_NoRoomRemaining:
	.string "Thanks for waiting!\p"
	.string "{PLAYER}, your PC BOXES are chock-\n"
	.string "full of {POKEMON}!\p"
	.string "You'll have to release some {POKEMON}\n"
	.string "if you want to catch more.\p"
	.string "Bye now!$"


Text_Bill_JustRanOutOfRoom:
	.string "Hi, {PLAYER}? It's me, BILL!\n"
	.string "Thanks for using my STORAGE SYSTEM.\p"
	.string "That last {POKEMON} you sent filled\n"
	.string "your PC BOXES up! Wow!\p"
	.string "Seriously, I know a stellar collection\n"
	.string "when I see it! Well done!\p"
	.string "However, if you want to catch more\n"
	.string "{POKEMON}, you'll have to release some…\p"
	.string "I just don't have the storage capacity\n"
	.string "to hold any more {POKEMON} for you!\p"
	.string "Though, I know a girl named BRIGETTE\n"
	.string "who might have some extra space…\l"
	.string "Well, for now, you're full up!\p"
	.string "Bye now!$"


InviteToSevii_Text_BillCall:
	.string "Hi, {PLAYER}? It's me, BILL!\n"
	.string "Thanks for using my STORAGE SYSTEM.\p"
	.string "I have a favor to ask…\p"
	.string "You know how the volcano in CINNABAR\n"
	.string "erupted and destroyed the town?\p"
	.string "Fortunately, everyone was evacuated\n"
	.string "in time and no one was hurt…\p"
	.string "Well, CINNABAR's volcano is part of\n"
	.string "a volcanic system that stretches to\l"
	.string "this little island far to the south.\p"
	.string "What island? ONE ISLAND, of course!\n"
	.string "It's down in the SEVII ISLANDS.\p"
	.string "MT. EMBER there erupted first, giving\n"
	.string "us a warning that CINNABAR was next.\p"
	.string "The damage was pretty bad in the SEVII\n"
	.string "ISLANDS, and they're still recovering.\p"
	.string "A friend invited me to THREE ISLAND.\n"
	.string "Well, in truth, he asked for my help…\p"
	.string "The last time I went to SEVII, I\n"
	.string "brought a strong TRAINER with me.\p"
	.string "This time I think it's even more vital\n"
	.string "to bring someone like that along.\p"
	.string "When you're not busy, would you\n"
	.string "please meet me on CINNABAR ISLAND?\p"
	.string "I'll be waiting for you in the\n"
	.string "{POKEMON} CENTER there.\p"
	.string "Thanks, {PLAYER}!\n"
	.string "See you soon!$"


