Text_Buena_RegularCall:
	.string "Hi, {PLAYER}!\n"
	.string "I'm BUENA!\p"
	.string "Bye-bye!$"


BuenaPhoneMorningAnswerText:
	.string "Hi, this is BUENA…\n"
	.string "Oh! Good morning, {PLAYER}!"
	.string "I'm kind of foggy in the morning…\p$"


BuenaPhoneDayAnswerText:
	.string "Hi, this is BUENA…\n"
	.string "Oh! Hi, {PLAYER}!\l"
	.string "Do you tune into BUENA's show?\p$"


BuenaPhoneMidnightAnswerText:
	.string "This is BUENA.\n"
	.string "I can't come to the phone right now.\l"
	.string "If you want to chat, tune into\l"
	.string "BUENA's PASSWORD on the radio and\l"
	.string "give me a call after midnight!$"


BuenaPhoneNiteAnswerText:
	.string "Hi, this is BUENA…\n"
	.string "Oh! Hi, {PLAYER}!\l"
	.string "I just got off work.\l"
	.string "Let me tell you, I'm exhausted!\p$"


BuenaPhoneMorningText:
	.string "{PLAYER}!\n"
	.string "Hi, it's BUENA!\l"
	.string "I got up early, so I decided to call!\p$"


BuenaPhoneDayText:
	.string "{PLAYER}!\n"
	.string "Hi, it's BUENA!\l"
	.string "I needed someone to chat with!\p$"


BuenaPhoneMidnightText:
	.string "{PLAYER}!\n"
	.string "Hi, it's BUENA!\l"
	.string "I'm just on my break.\p$"


BuenaPhoneNiteText:
	.string "{PLAYER}!\n"
	.string "Hi, it's BUENA!\l"
	.string "I couldn't sleep, so I called you.\p$"


BuenaPhoneRocketText:
	.string "Oh. Hi, {PLAYER}\n!"
	.string "You are how?\p"
	.string "Aiyee! This isn't the time for me to\n"
	.string "be cracking silly gag greetings!\l"
	.string "The RADIO TOWER is in deep trouble!\l"
	.string "{PLAYER}, you'd better be careful!$"


BuenaPhoneWentOutWithBenText:
	.string "The other day, I went out to eat\n"
	.string "with DJ BEN!\l"
	.string "Isn't it great?\l"
	.string "Not only that, he said the music on\l"
	.string "my program is cool!\l"
	.string "Oh, wow! Like, what should I do?\p"
	.string "…Oops, I have to get ready for my show!\n"
	.string "I'll catch you later!$"


BuenaPhoneReceptionistText:
	.string "You know the receptionist at the RADIO TOWER?\n"
	.string "'Welcome,' is all she ever says.\l"
	.string "But she's really the chattiest person\l"
	.string "at the RADIO TOWER.\l"
	.string "So she must be holding back.\l"
	.string "Isn't that fun to know?\l"
	.string "Catch you later!$"


BuenaPhoneLuckyNumberShowText:
	.string "Tell me, {PLAYER}.\n"
	.string "Have you ever won a prize on the\l"
	.string "LUCKY NUMBER SHOW?\l"
	.string "REED moans that he's never won,\l"
	.string "so he vows to keep the show on the\l"
	.string "air till he does.\l"
	.string "Let's chat again!$"


BuenaPhoneStressedFromWorkText:
	.string "You know, last night…\n"
	.string "I was so stressed out from work,\l"
	.string "I ate a ton of junk food!\l"
	.string "MARY and I have this deal about\l"
	.string "losing weight…\p"
	.string "This won't do…\p"
	.string "Huh? What's the weight?\n"
	.string "That has to be a total secret!\l"
	.string "MARY weighs…\p"
	.string "Aiyee! M-MARY!\p"
	.string "Uh… Um… I… Sorry-- wrong number!$"


BuenaPhoneProfessorOakText:
	.string "Yesterday, PROF. OAK was in the\n"
	.string "studio to tape his show.\l"
	.string "So I went over and introduced myself.\l"
	.string "Get this--he tunes in to my program!\l"
	.string "Oh! Here comes PROF.OAK again!\p"
	.string "I'm going to chat him up again!\n"
	.string "Catch you later!$"


BuenaPhoneGotAColdText:
	.string "…Cough, cough!\p"
	.string "Uhm sorry uh got uh code dite now.\n"
	.string "Buh uma pro so uh hav to cover id ub\l"
	.string "so no un notice while uhm on air.\p"
	.string "Uh fidz muh voice now.\p"
	.string "I'll catch you on the fly.\n"
	.string "This has been BUENA!$"


BuenaPhoneRadioCardQuestionsText:
	.string "Hey, {PLAYER}.\n"
	.string "You won that RADIO CARD by beating\l"
	.string "the quiz at the reception desk, didn't you?\p"
	.string "Guess what? I made up the questions!\n"
	.string "…Were they too easy for you?\l"
	.string "Well, let's chat again!$"


BuenaPhonePikachuFanClubText:
	.string "I'm elated that more people are\n"
	.string "taking part in my PASSWORD show.\l"
	.string "But when PIKACHU was the password,\l"
	.string "it was uh… whew… overwhelming.\p"
	.string "FAN CLUB people came out in droves,\n"
	.string "shouting 'PIKACHU!' over and over.\l"
	.string "I mean, they were loud.\p"
	.string "Anyone tuning in around then must\n"
	.string "have been shocked by the racket!\p"
	.string "Anyway, back to work for me!\n"
	.string "Let's chat again!$"


BuenaPhoneRadioTowerDirectorText:
	.string "Guess what?\n"
	.string "The RADIO TOWER's DIRECTOR is a big\l"
	.string "fan of TV!\p"
	.string "A while ago, a fashion show on TV\n"
	.string "said that black suits were in.\l"
	.string "Now all he wears are black suits.\l"
	.string "But it's a secret that our DIRECTOR\l"
	.string "is a TV fan, so if you see him,\l"
	.string "don't you dare mention it!\p"
	.string "Oh! The DIRECTOR will be here soon!\n"
	.string "Later! Tune into my show!$"


BuenaPhoneWhenDoYouRelaxText:
	.string "{PLAYER}, tell me.\n"
	.string "When do you relax the most?\l"
	.string "For me, it has to be in the studio\l"
	.string "right after my show, enjoying a\l"
	.string "nice cup of tea.\l"
	.string "It's so pleasant that it gradually\l"
	.string "makes me drowsy…\l"
	.string "… … …\l"
	.string "… … …Zzz\p"
	.string "Oops, I drifted off just thinking\n"
	.string "about it! How, uh… embarrassing!\l"
	.string "Please forget this happened! Later!$"


BuenaPhoneStarterPokemonText:
	.string "{PLAYER}, what was the first {POKEMON}\n"
	.string "you ever caught?\l"
	.string "…Oh, really?\l"
	.string "I've seen lots of {POKEMON} around,\l"
	.string "but I've never caught one.\p"
	.string "I should give it a try sometime.\p"
	.string "Did you know that the first {POKEMON}\n"
	.string "MARY caught was a DROWZEE?\l"
	.string "Isn't that so out of character?\l"
	.string "But MARY's DROWZEE kept making her\l"
	.string "fall asleep on the job, so she traded\l"
	.string "with a fan for a MEOWTH.\p"
	.string "Let's chat about {POKEMON} again!"
	.string "Bye-bye!$"


BuenaPhoneCompanyVacationText:
	.string "Guess what? All of us from\n"
	.string "the RADIO TOWER are going on\l"
	.string "a company vacation to the RADIO TOWER\l"
	.string "in LAVENDER.\p"
	.string "We're wasting our vacation on a trip\n"
	.string "to another RADIO TOWER?\p"
	.string "I'd much rather go to the beach!\n"
	.string "{PLAYER}, I hope you have enough fun\l"
	.string "fun for both of us on your journey!\l"
	.string "Bye-bye!$"


BuenaPhoneBenAndFernText:
	.string "Did you know…?\p"
	.string "BEN and FERN talk on the phone\n"
	.string "for hours about what {POKEMON} music\l"
	.string "should play on different days of the week.\p"
	.string "One time, FERN's rapping style\n"
	.string "kind of rubbed off on BEN weirdly.\p"
	.string "So we ended up enduring BEN's\n"
	.string "silly, chilly, a willy-nilly jive-\l"
	.string "talking shtick for a while.\l"
	.string "Let's chat again!$"


BuenaPhoneGoingShoppingText:
	.string "I'm going shopping with MARY and LILY soon.\p"
	.string "It'll be great if GOLDENROD DEPT.\n"
	.string "STORE has a sale on when we go…\l"
	.string "{PLAYER}, maybe we can hook up too!\l"
	.string "Catch you later!$"


BuenaPhoneFavoriteSlotMachineAnswerText:
	.string "I'm thinking of going\nto the GAME CORNER tomorrow.\l"
	.string "It's been a while.\l"
	.string "You see, I have my favorite machine…\l"
	.string "It pays out a lot, I kid you not!\l"
	.string "Huh? Nuh-uh, it's my secret!\l"
	.string "You have to find it yourself!\l"
	.string "Catch you later!$"


BuenaPhonePokegearAnswerText:
	.string "Hey, {PLAYER}. You use your {POKE}GEAR\n"
	.string "to listen to the radio, right?\l"
	.string "I heard that you can even display\l"
	.string "town maps with {POKE}GEAR.\p"
	.string "I have a bad sense of direction,\n"
	.string "so {POKE}GEAR would be handy…\p"
	.string "Anyway, thanks for calling! Later!$"


BuenaPhoneCoopedUpInRadioTowerAnswerText:
	.string "Is it sunny outside today?\n"
	.string "When you're cooped up in the\l"
	.string "RADIO TOWER as much as I am,\l"
	.string "you lose touch with the outside.\l"
	.string "It can be boring.\l"
	.string "Please call again!$"

