Text_Pokegear_Elm_Start::
	.string "Hello, {PLAYER}?\n"
	.string "Try not to overdo it.\p"
	.string "Be sure to heal your {POKEMON} if\n"
	.string "they are hurt.$"


Text_Pokegear_Elm_SawMrPokemon::
	.string "Hello, {PLAYER}?\n"
	.string "Did you meet MR. {POKEMON}?\p"
	.string "Great!\n"
	.string "Come back safely!$"


Text_Pokegear_Elm_MonWasStolen::
	.string "{PLAYER}?\n"
	.string "I'm very upset right now.\p"
	.string "We had a {POKEMON} stolen from here.\n"
	.string "How could anyone do that?$"


Text_Pokegear_Elm_CheckingEgg::
	.string "Hello, {PLAYER}?\n"
	.string "We're checking the EGG now.\p"
	.string "It does appear to be a {POKEMON}\n"
	.string "EGG.$"


Text_Pokegear_Elm_SeeAssistant::
	.string "Hello, {PLAYER}?\n"
	.string "Did you see my assistant?\p"
	.string "He's at the {POKEMON} CENTER in\n"
	.string "VIOLET CITY.$"


Text_Pokegear_Elm_EggUnhatched::
	.string "Hello, {PLAYER}?\n"
	.string "How's the EGG?\l"
	.string "Has anything changed?\p"
	.string "If anything happens, please call.$"


Text_Pokegear_Elm_EggHatched::
	.string "Hello, {PLAYER}?\n"
	.string "How is the EGG?\p"
	.string "What? It hatched?\n"
	.string "Wow! What kind of {POKEMON} is it?\p"
	.string "Please come show me now!$"


Text_Pokegear_Elm_Discovery1::
	.string "Hello, {PLAYER}?\n"
	.string "I just made a new discovery.\p"
	.string "The time it takes for an EGG to\n"
	.string "hatch depends on the {POKEMON}.$"


Text_Pokegear_Elm_Discovery2::
	.string "Hello, {PLAYER}?\p"
	.string "It's still a mystery what kinds\n"
	.string "of moves hatched {POKEMON} have.\l"
	.string "We're investigating that now.$"


Route30_Text_ElmCall:
	.string "H-hello? {PLAYER}?\n"
	.string "It's a disaster!\p"
	.string "Uh, um, it's just terrible!\p"
	.string "What should I do?\n"
	.string "It… Oh, no…\p"
	.string "Please get back here now!$"


VioletCity_Text_ElmCall:
	.string "Hello, {PLAYER}?\n"
	.string "We discovered something about\l"
	.string "the EGG!\p"
	.string "My assistant is at the {POKEMON}\n"
	.string "CENTER in VIOLET CITY.\l"
	.string "Could you talk to him?$"


RadioTower_Text_ElmCall:
	.string "{PLAYER}, how are things going?\p"
	.string "I called because something weird is\n"
	.string "happening with the radio broadcasts.\p"
	.string "They were talking about TEAM ROCKET.\p"
	.string "Maybe TEAM ROCKET has returned.\n"
	.string "No, that just can't be true.\p"
	.string "Sorry to bug you.\n"
	.string "Take care!$"


MasterBall_Text_ElmCall:
	.string "Hello, {PLAYER}?\p"
	.string "I have something here for you.\n"
	.string "Could you swing by my LAB?\p"
	.string "See you later!$"

