Matchcall_Irwin_Answer_Morn::
	.string  "Hello? IRWIN here…\n"

	.string "Hey, {PLAYER}!\p$"



Matchcall_Irwin_Answer_Day::
	.string  "Hello? IRWIN here…\n"

	.string "Wow, {PLAYER}!\p$"



Matchcall_Irwin_Answer_Night::
	.string  "Hello? IRWIN here…\n"

	.string "Yippee, {PLAYER}!\p$"



Matchcall_Irwin_Call_Morn::
	.string  "Uh, hello. {PLAYER}?\n"

	.string "It's your pal, IRWIN!\p$"



Matchcall_Irwin_Call_Day::
	.string  "Uh, hello. {PLAYER}?\n"

	.string "It's your buddy IRWIN!\p$"



Matchcall_Irwin_Call_Night::
	.string  "Uh, hello. {PLAYER}?\n"

	.string "It's your sidekick IRWIN!\p$"



Matchcall_Irwin_Hangup::
	.string  "I hate having to hang up on you!\n"

	.string "Call you later!$"



Matchcall_Irwin_Rocket_Takeover::
	.string  "{PLAYER}, have you heard?\n"

	.string "GOLDENROD's RADIO TOWER has been\l"

	.string "taken over by TEAM ROCKET!\l"

	.string "…Um… What's TEAM ROCKET?\p$"



Matchcall_Irwin_Plain_Badge::
	.string  "{PLAYER}, I heard!\n"

	.string "You defeated that WHITNEY?\l"

	.string "It makes me proud to be your friend!\p$"



Matchcall_Irwin_Jasmine_Returned::
	.string  "Hey, I heard about you!\n"

	.string "You saved that {POKEMON} at the\l"

	.string "LIGHTHOUSE, didn't you?\l"

	.string "{PLAYER}, I wish you'd come see me\l"

	.string "when I'm sick in bed with a cold!\p$"



Matchcall_Irwin_Rocket_Hideout::
	.string  "I heard, I heard, I heard!\n"

	.string "You smashed TEAM ROCKET's hideout!\l"

	.string "You're like a movie hero, even!\l"

	.string "But um… What was TEAM ROCKET?\p$"



Matchcall_Irwin_Radio_Tower::
	.string  "I heard, I heard, I heard!\n"

	.string "About your heroic liberation of the\l"

	.string "RADIO TOWER!\l"
	.string "You rock so hard!\p$"



Matchcall_Irwin_Rising_Badge::
	.string  "I saw, I saw!\n"

	.string "I saw you go into the DRAGON'S DEN!\l"

	.string "I'm certain you passed!\l"
	.string "Aww, no need to be modest!\l"
	.string "You can't fail!\p$"



Matchcall_Irwin_Elite_Four::
	.string  "Yesterday, I went out to NEW BARK TOWN.\n"

	.string " There was a lady who looked a lot like you, {PLAYER}.\p"

	.string "What? That lady was your mom?\n"

	.string "Aww, I should've introduced myself!\l"

	.string "I bet your mom's really proud of all that you've\l"
	.string "accomplished.\p"

	.string "Heh, put it this way. I'd be proud if I were your\n"
	.string "mom, believe me!\p$"



Matchcall_Irwin_Vermillion::
	.string  "I saw, I saw, I saw!\n"

	.string "You striding onto a ship, {PLAYER}!\l"

	.string "I can't get over how good you look\l"

	.string "with the sea as your backdrop!\p$"



Matchcall_Irwin_Magnet_Train::
	.string  "I heard, I heard!\n"

	.string "You got a MAGNET TRAIN PASS!\l"

	.string "When I saw you departing on the ship, I felt sad\l"
	.string "that I wouldn't be able to see you for a while.\l"

	.string "But since you have that PASS, you can zip back anytime!\l"
	.string "That's reassuring!\l"

	.string "What? You can FLY back anytime?\l"

	.string "What do you mean by FLY?\p$"



Matchcall_Irwin_Snorlax::
	.string  "I saw, I saw!\n"

	.string "You waking up SNORLAX!\l"

	.string "I was watching you from afar, so I couldn't tell what\l"
	.string "you did exactly.\l"

	.string "Did you play a flute to wake it?\l"

	.string "Wow! That's like magic!\p$"



Matchcall_Irwin_Mt_Silver::
	.string  "I hear rumors about you all over the place.\n"

	.string "It just makes me sigh, {PLAYER}.\l"

	.string "How did you get so strong?\l"

	.string "Go for the world championship now!\l"

	.string "I'll always be cheering you on!\p$"



Matchcall_Irwin_Called_Right_Away::
	.string  "Hehe, I called right away!\n"

	.string "I think we can be good friends!$"



Matchcall_Irwin_Fog_Badge::
	.string  "I saw, I heard!\n"

	.string "You beat MORTY of ECRUTEAK GYM!\l"

	.string "Th-that's just incredible!\l"

	.string "I actually went to the GYM's entrance\l"

	.string "to cheer you on.\l"
	.string "Did you know that?\l"

	.string "But everyone was floating,\l"

	.string "and there were ghosts all over!\l"

	.string "So I chickened out and took off for home…\p$"



Matchcall_Irwin_Marsh_Badge::
	.string  "{PLAYER}, I heard!\n"

	.string "You're kicking up a mighty ruckus\l"

	.string "over in KANTO!\l"
	.string "What a glorious rampage it must be!\l"

	.string "You so rock!\p$"



Matchcall_Irwin_Escapades::
	.string  "Hearing about your escapades\n"
	.string "rocks my soul!\l"
	.string "It sure does!\p$"



Matchcall_Irwin_Good_Match::
	.string  "I'm so glad you called!\n"

	.string "I was just about to call you too!\l"

	.string "I guess we must be a good match!\p$"



Matchcall_Irwin_So_Much_To_Chat_About::
	.string  "How are you?\n"

	.string "What are you doing?\l"

	.string "Where are you?\l"

	.string "How many BADGES do you have now?\l"

	.string "How much money have you saved?\l"

	.string "How's your mom?\l"

	.string "Have you got lots of {POKEMON}?\l"

	.string "Is it going to be sunny tomorrow?\p"

	.string "Arrgh, there's so much I want to\n"

	.string "chat about!\l"
	.string "This is going nowhere!\p$"


