Matchcall_Kenji_Answer_Morn::
	.string "KENJI here…\n"

	.string "{PLAYER}!\l"
	.string "Beautiful morning, hey?\p$"



Matchcall_Kenji_Answer_Day::
	.string "KENJI here…\n"


	.string "{PLAYER}!\l"
	.string "Beautiful weather, hey?\p$"



Matchcall_Kenji_Answer_Night::
	.string "KENJI here…\n"


	.string "{PLAYER}!\l"
	.string "Beautiful moonlight, hey?\p$"



Matchcall_Kenji_Call::
	.string  "Hey, {PLAYER}!\n"
	.string "This is KENJI!\p$"



Matchcall_Kenji_Hangup::
	.string  "Anyway, we'll chat again!$"



Matchcall_Kenji_Generic::
	.string  "Are you still on your journey?\n"

	.string "I remain dedicated to my training.\l"

	.string "Oooooaaarrrgh!\p$"



Matchcall_Kenji_Another_Time::
	.string  "I'm in training now.\n"

	.string "I apologize, but call me back\l"
	.string "another time.\l"

	.string "Oooooaaarrrgh!\p$"



Matchcall_Kenji_Chat_Tomorrow::
	.string  "I apologize, but I don't have time\n"

	.string "to chat while I am in training!\l"

	.string "I'll have time to chat tomorrow!\l"

	.string "Yiiihah!\p$"



Matchcall_Kenji_Call_Morning::
	.string  "I plan to take a lunch break,\n"
	.string "so come see me then!\l"
	.string "Ayiiiyah!\p$"



Matchcall_Kenji_Gift::
	.string  "I'm taking a break on ROUTE 45!\n"

	.string "Why not drop by if you are free?\p$"



Matchcall_Kenji_Call_Night::
	.string  "I rested up over my lunch break.\n"

	.string "Now it's time to resume training!\l"

	.string "Oooryaah!\p$"


