Text_Pokegear_Mom_Start:
	.string "Hello?\n"
	.string "Oh, hi, {PLAYER}!\p"
	.string "Wasn't PROF. ELM waiting for you?$"


Text_Pokegear_Mom_GotMon:
	.string "Hello?\n"
	.string "Oh, hi, {PLAYER}!\p"
	.string "You're on a big mission for PROF. ELM?\n"
	.string "Be good!$"


Text_Pokegear_Mom_GaveEggToElm:
	.string "Hello?\n"
	.string "Oh, hi, {PLAYER}!\p"
	.string "If you're done with your errand,\n"
	.string "come on home, dear.$"


Text_Pokegear_Mom_PhoneBanking_Question:
	.string "Hello?\n"
	.string "…… {PLAYER}?\p"
	.string "I heard from PROF. ELM that you\n"
	.string "went on a long trip.\p"
	.string "I wish you would have told me…\p"
	.string "What about money?\n"
	.string "Do you want me to save it?$"


Text_Pokegear_Mom_RegularCall_WorkingHard:
	.string "Hello?\n"
	.string "Oh, hi, {PLAYER}! Working hard?\p$"


Text_Pokegear_Mom_RegularCall_NeverGoneThere:
	.string "Really, you're in {STR_VAR_1}?\p"
	.string "I've never gone there.\n"
	.string "That's kind of neat, {PLAYER}.\p$"


Text_Pokegear_Mom_RegularCall_NewBark:
	.string "What? You're in {STR_VAR_1}?\n"
	.string "Come see your MOM sometime!\p$"


Text_Pokegear_Mom_RegularCall_Cherrygrove:
	.string "You're visiting {STR_VAR_1}?\n"
	.string "How about coming home for a bit?\p$"


Text_Pokegear_Mom_RegularCall_Landmark:
	.string "Oh, so you're in {STR_VAR_1}?\p"
	.string "Isn't that where {STR_VAR_2}\n"
	.string "is? Did you go take a look?\p$"


Text_Pokegear_Mom_RegularCall_Route:
	.string "Wow, you're in {STR_VAR_1}?\n"
	.string "Good luck on your {POKEMON} quest!\p$"


Text_Pokegear_Mom_RegularCall_Determined:
	.string "That sounds really tough.\p"
	.string "But, {PLAYER}, I know you're really\n"
	.string "determined. You'll be okay, right?\p$"


Text_Pokegear_MomBank_HasNoMoneySavingDisabled:
	.string "Oh, {PLAYER}, you're not saving any\n"
	.string "money. Would you like to start saving?$"


Text_Pokegear_MomBank_HasNoMoneySavingEnabled:
	.string "It's important to save your money.\n"
	.string "Do you want to keep on saving?$"


Text_Pokegear_MomBank_HasMoneySavingDisabled:
	.string "By the way, you've saved up ¥{STR_VAR_1}.\n"
	.string "Want to start saving again?$"


Text_Pokegear_MomBank_HasMoneySavingEnabled:
	.string "By the way, you've saved up ¥{STR_VAR_1}.\n"
	.string "Do you want to keep on saving?$"


Text_Pokegear_MomBank_EnableSaving:
	.string "Okay, I'll save your money.\p$"


Text_Pokegear_MomBank_DisableSaving:
	.string "Okay, I won't save your money.\p$"


Text_Pokegear_Mom_RootingForYou:
	.string "{PLAYER}, keep it up!\n"
	.string "I'm rooting for you, baby!$"


BoughtItem_Text_MomCall:
	.string "Hi, {PLAYER}!\n"
	.string "How are you?\p"
	.string "I found a useful item shopping, so\n"
	.string "I bought it with your money. Sorry!\p"
	.string "It's in your PC.\n"
	.string "You'll like it!$"


BoughtDoll_Text_MomCall:
	.string "Hi, {PLAYER}!\n"
	.string "How are you?\p"
	.string "While shopping today, I saw this\n"
	.string "adorable doll, so I bought it with\l"
	.string "your money. Sorry!\p"
	.string "It's in your room.\n"
	.string "You'll love it!$"

