Matchcall_Todd_Goldenrod_Dept_Sale::
	.string "This is it--the one\n"
	.string "we've all been waiting for!\p"

	.string "GOLDENROD DEPT. STORE's bargain sale\n"
	.string "is on now!\l"

	.string "Want it cheap?\l"
	.string "Want it lots?\l"

	.string "Don't miss this GOLDENROD chance!\l"

	.string "Huh? I sound like a huckster?\l"

	.string "Well, yeah. I was mimicking them…\p"

	.string "Anyway, you've got to get there\n"
	.string	"as soon as you can!$"


Matchcall_Todd_Remind_Goldenrod_Dept_Sale::
	.string "Haven't you gone to GOLDENROD\n"
	.string "DEPT. STORE?\l"
	.string "I've scoped it out already!\l"

	.string "They had some real bargains.\l"

	.string "You should get there quickly.$"

